version: '3.8'
services:
  postgres:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_USER: '${POSTGRES_USER:-postgres}'
      POSTGRES_PASSWORD: '${POSTGRES_PASSWORD:-postgres}'
      POSTGRES_DB: '${POSTGRES_DB:-yonsei}'
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - 5432:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
  osrm:
    build:
      context: ./osrm
      dockerfile: Dockerfile
    entrypoint: osrm-routed --algorithm mld /data/yonsei_processed.osrm
    restart: always
    ports:
      - 6000:5000
    volumes:
      - ./osrm/map:/data

